sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_b2940f5a2a73_key -iv $encrypted_b2940f5a2a73_iv
    -in pristine-atom-252001-b16ccea9f557.json.enc -out pristine-atom-252001-b16ccea9f557.json
    -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file pristine-atom-252001-b16ccea9f557.json
  - gcloud config set project pristine-atom-252001
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t seriousbob/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true seriousbob/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master