sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_b2940f5a2a73_key -iv $encrypted_b2940f5a2a73_iv
  -in pristine-atom-252001-b16ccea9f557.json.enc -out pristine-atom-252001-b16ccea9f557.json
  -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-acount.json
